blueprint:
  name: Pura Diffusers as HomeKit Humidifiers
  description: >
    Expose multiple Pura diffuser entities as independent humidifiers in HomeKit using intensity mapping and fragrance slot control.
  domain: automation
  input:
    fragrance_entities:
      name: Fragrance Selector Entities
      description: List of fragrance slot entities (controls on/off via slot selection).
      selector:
        entity:
          multiple: true
          integration: pura
    intensity_entities:
      name: Intensity Selector Entities
      description: List of intensity entities (controls scent strength).
      selector:
        entity:
          multiple: true
          integration: pura
    names:
      name: Custom Names
      description: List of custom names (one per diffuser, same order).
      default: []
      selector:
        object:

mode: parallel
max: 10

variables:
  fragrance_entities: !input fragrance_entities
  intensity_entities: !input intensity_entities
  custom_names: !input names

trigger:
  - platform: state
    for:
      seconds: 1
    entity_id: !input intensity_entities

condition: []

action:
  - repeat:
      count: "{{ intensity_entities | length }}"
      sequence:
        - variables:
            fragrance: "{{ fragrance_entities[repeat.index - 1] }}"
            intensity: "{{ intensity_entities[repeat.index - 1] }}"
            name: "{{ custom_names[repeat.index - 1] | slugify }}"
            humidifier: "humidifier.{{ custom_names[repeat.index - 1] | slugify }}_humidifier"

        # Map intensity to humidity sensor value
        - service: python_script.set_state
          data:
            entity_id: "sensor.{{ name }}_humidity"
            state: >
              {% set s = states(intensity) %}
              {% if s == 'subtle' %} 33
              {% elif s == 'medium' %} 66
              {% elif s == 'strong' %} 100
              {% else %} 0 {% endif %}
            attributes:
              unit_of_measurement: "%"
              device_class: humidity

        # Map humidity back to diffuser state
        - choose:
            - conditions:
                - condition: or
                  conditions:
                    - condition: numeric_state
                      entity_id: "{{ humidifier }}"
                      attribute: humidity
                      below: 1
                    - condition: state
                      entity_id: "{{ humidifier }}"
                      state: "off"
              sequence:
                - service: select.select_option
                  target:
                    entity_id: "{{ fragrance }}"
                  data:
                    option: "off"
                - service: select.select_option
                  target:
                    entity_id: "{{ intensity }}"
                  data:
                    option: "off"

            - conditions:
                - condition: numeric_state
                  entity_id: "{{ humidifier }}"
                  attribute: humidity
                  below: 34
              sequence:
                - service: select.select_option
                  target:
                    entity_id: "{{ fragrance }}"
                  data:
                    option: "slot 1"
                - service: select.select_option
                  target:
                    entity_id: "{{ intensity }}"
                  data:
                    option: "subtle"

            - conditions:
                - condition: numeric_state
                  entity_id: "{{ humidifier }}"
                  attribute: humidity
                  below: 67
              sequence:
                - service: select.select_option
                  target:
                    entity_id: "{{ fragrance }}"
                  data:
                    option: "slot 1"
                - service: select.select_option
                  target:
                    entity_id: "{{ intensity }}"
                  data:
                    option: "medium"

            - conditions:
                - condition: numeric_state
                  entity_id: "{{ humidifier }}"
                  attribute: humidity
                  above: 66
              sequence:
                - service: select.select_option
                  target:
                    entity_id: "{{ fragrance }}"
                  data:
                    option: "slot 1"
                - service: select.select_option
                  target:
                    entity_id: "{{ intensity }}"
                  data:
                    option: "strong"
